#!/bin/bash
# Auto-update build info before each commit

set -e

APP_JS="app.js"
INDEX_HTML="index.html"

# Use current HEAD as stable reference in build info.
COMMIT_HASH=$(git rev-parse --short=7 HEAD)

DAY=$(date '+%-d')
MONTH_NUM=$(date '+%-m')
YEAR=$(date '+%Y')
HM=$(date '+%H:%M')

case "$MONTH_NUM" in
  1) MONTH_NAME="januar" ;;
  2) MONTH_NAME="februar" ;;
  3) MONTH_NAME="mars" ;;
  4) MONTH_NAME="april" ;;
  5) MONTH_NAME="mai" ;;
  6) MONTH_NAME="juni" ;;
  7) MONTH_NAME="juli" ;;
  8) MONTH_NAME="august" ;;
  9) MONTH_NAME="september" ;;
  10) MONTH_NAME="oktober" ;;
  11) MONTH_NAME="november" ;;
  12) MONTH_NAME="desember" ;;
  *) MONTH_NAME="ukjent" ;;
esac

BUILD_TIME="${DAY}. ${MONTH_NAME} ${YEAR} ${HM}"
CACHE_BUSTER="v$(date +%s)"

sed -E -i.bak "s|const BUILD_COMMIT = '[^']*'|const BUILD_COMMIT = '${COMMIT_HASH}'|" "$APP_JS"
sed -E -i.bak "s|const BUILD_TIME = '[^']*'|const BUILD_TIME = '${BUILD_TIME}'|" "$APP_JS"
rm -f "$APP_JS.bak"

sed -E -i.bak "s|\?v=[^\"']+|?v=${CACHE_BUSTER}|g" "$INDEX_HTML"
rm -f "$INDEX_HTML.bak"

git add "$APP_JS" "$INDEX_HTML"

exit 0
